export const stages = [
  { id: 'discovery', title: 'Discovery', ai: 'Research the problem, inventory the source, draft requirements.', human: 'Confirm scope, outcomes, assumptions and accountable owners.', evidence: 'Charter, requirements, research sources and open questions.', gate: 'Scope acceptance' },
  { id: 'design', title: 'Design', ai: 'Compare options and propose content models, contracts and architecture.', human: 'Assess tradeoffs and select the design.', evidence: 'Versioned architecture decisions, data flows and API contracts.', gate: 'Design review' },
  { id: 'design-security', title: 'Design security', ai: 'Draft the threat model, abuse cases and testable controls.', human: 'Accept or reject the security design before implementation.', evidence: 'Access matrix, findings and decision bound to design version.', gate: 'Human security approval' },
  { id: 'planning', title: 'Sprint planning', ai: 'Break outcomes into stories, estimate uncertainty and plan dependencies.', human: 'Review capacity, risks and the sprint commitment.', evidence: 'Stories, acceptance criteria, sprint plan and approval.', gate: 'Human sprint approval' },
  { id: 'implementation', title: 'Implementation', ai: 'Implement a bounded task, update documentation and keep progress records.', human: 'Steer the work and review the proposed change.', evidence: 'Task contract, commit/PR, documentation and execution record.', gate: 'Accepted design + sprint required' },
  { id: 'verification', title: 'Verification', ai: 'Run deterministic checks, investigate failures and prepare reports.', human: 'Assess evidence quality, limitations and unresolved defects.', evidence: 'Raw check output, hashes, test results and reconciliation.', gate: 'Required checks pass' },
  { id: 'code-security', title: 'Code security', ai: 'Propose code/configuration findings and remediation.', human: 'Review actual code and controls; accept the exact reviewed commit.', evidence: 'Manual review, scans, negative tests and retest chain.', gate: 'Human code-security approval' },
  { id: 'showcase', title: 'Sprint & MVP review', ai: 'Assemble the demonstration, metrics and evidence index.', human: 'Review the showcase and accept or reject sprint and MVP outcomes.', evidence: 'Demo, planned-versus-actual summary and separate decisions.', gate: 'Human outcome approval' },
  { id: 'release', title: 'Production release', ai: 'Prepare release artifacts, runbooks and readiness evidence.', human: 'Authorize the reviewed artifact after all readiness gates pass.', evidence: 'Artifact digest, security decisions, restore/load results and release approval.', gate: 'Human release authorization' },
  { id: 'operations', title: 'Operations', ai: 'Summarize incidents, investigate causes and propose corrective work.', human: 'Own incident decisions, recovery and service acceptance.', evidence: 'Timeline, logs, recovery results and corrective stories.', gate: 'Recovery acceptance' },
]

export const templateDefinitions = [
  { id: 'project-charter', title: 'Project charter', stage: 'discovery', description: 'Outcomes, boundaries, milestones and ownership.', example: '# Illustrative charter excerpt\nProject: Headless CMS\nOutcome: Editors publish content through a headless API.\nFirst source: synthetic Drupal-style fixture SYN-001.\nLater source: AEM after separate assessment.\nExcluded from MVP 1: live migration and production deployment.\nHuman decision: Pending (example only).', },
  { id: 'requirement', title: 'Requirement', stage: 'discovery', description: 'Observable acceptance criteria and measurable targets.', example: '# Illustrative requirement excerpt\nID: REQ-CMS-002\nOutcome: Public readers see only public, published articles.\nGiven a private draft, when an anonymous client requests it, then no private content is returned.\nEvidence expected: negative REST and relationship-expansion tests.\nActual result: Not executed in this example.', },
  { id: 'architecture-decision', title: 'Architecture decision', stage: 'design', description: 'Options, rationale, consequences and source evidence.', example: '# Illustrative architecture excerpt\nProposed choice: Payload + PostgreSQL.\nReason: Extend an existing editor and content platform.\nPilot: editor-to-public-API journey and synthetic importer.\nUncertainty: actual Drupal schema and custom modules are unknown.\nHuman decision: Pending (example only).', },
  { id: 'design-security-review', title: 'Design security review', stage: 'design-security', description: 'Threats and control requirements before code.', example: '# Illustrative design review excerpt\nScope: local CMS and synthetic import.\nRisk: drafts leak through nested API reads.\nControl: apply publication and visibility checks to every read path.\nRequired evidence: anonymous direct/list/nested/revision denials.\nSecurity decision: Pending (example only).', },
  { id: 'story', title: 'User story', stage: 'planning', description: 'User outcome, dependencies, checks and demo.', example: '# Illustrative story excerpt\nAs an editor, I want to save a draft so I can review it before publication.\nGiven an authenticated editor, when a draft is saved and reopened, then its title/body persist.\nNegative criterion: the editor cannot publish or change roles.\nDemo: edit, save, reload, show denied publish attempt.\nAcceptance: Pending (example only).', },
  { id: 'sprint-plan', title: 'Sprint plan', stage: 'planning', description: 'Goal, capacity, stories and human start gate.', example: '# Illustrative sprint excerpt\nGoal: local CMS vertical slice.\nStories: environment, editorial permissions, sample import, showcase.\nCapacity: proposed; no proven AI velocity.\nStart: accepted design and human sprint-plan decision required.\nSprint decision: Pending (example only).', },
  { id: 'ai-task', title: 'AI task contract', stage: 'implementation', description: 'Bounded scope, tool permissions and deterministic checks.', example: '# Illustrative AI task excerpt\nObjective: implement private draft reads.\nAllowed scope: article access rules and focused negative tests.\nInputs: synthetic content only.\nChecks: typecheck and API authorization tests.\nOutput: diff, raw results, docs, limitations.\nThe agent cannot approve its own work.', },
  { id: 'verification-report', title: 'Verification report', stage: 'verification', description: 'Expected versus actual results and retests.', example: '# Illustrative verification excerpt\nCriterion: anonymous private draft access denied.\nCommand: run negative REST checks.\nExpected: 403/404, no draft body.\nActual: Not executed in this example.\nEvidence: record exact output and commit after execution.', },
  { id: 'evidence-record', title: 'Audit evidence record', stage: 'verification', description: 'Provenance, reproducibility, hashes and retention.', example: '# Illustrative evidence excerpt\nPurpose: prove unchanged re-import produces no duplicate records.\nSource classification: synthetic.\nCommit/tool/run identifiers: record actual values.\nCounts and SHA-256: capture after execution, never invent.\nApproval: separate human review record.', },
  { id: 'migration-run', title: 'Migration run', stage: 'verification', description: 'Source mapping, checkpoints and count reconciliation.', example: '# Illustrative migration excerpt\nSource: synthetic Drupal-style fixture.\nSelected = created + updated + skipped + rejected + conflicted + failed.\nInput total = selected + excluded.\nRequired checks: references, privacy, media hashes and rerun behavior.\nObserved counts: unavailable until this run executes.', },
  { id: 'code-security-review', title: 'Code security review', stage: 'code-security', description: 'Review actual implementation against accepted design.', example: '# Illustrative code review excerpt\nControl: editors cannot grant themselves administrator privileges.\nInspect: user collection permissions and raw request guard.\nEvidence: role-escalation request denied; role unchanged.\nReviewed commit: required.\nHuman security decision: Pending (example only).', },
  { id: 'sprint-mvp-review', title: 'Sprint & MVP review', stage: 'showcase', description: 'Showcase, meaningful metrics and separate acceptance decisions.', example: '# Illustrative showcase excerpt\nDemo: import, edit draft, publish as publisher, read anonymously.\nReport: planned/completed/accepted stories and actual evidence.\nLimitations: synthetic source only; production readiness not demonstrated.\nSprint outcome: Pending.\nMVP acceptance: Pending.\nThese are separate human decisions.', },
  { id: 'production-release', title: 'Production release', stage: 'release', description: 'Readiness checklist, artifact identity and release decision.', example: '# Illustrative release excerpt\nArtifact: bind to reviewed commit/build digest.\nRequired: functional/security acceptance, load/restore evidence, monitoring, operational owners.\nMigration: real-source rehearsal and reconciliation.\nRelease authorization: Pending.\nA successful build alone is insufficient.', },
  { id: 'incident-recovery', title: 'Incident & recovery', stage: 'operations', description: 'Timeline, impact, recovery and corrective work.', example: '# Illustrative recovery excerpt\nScenario: delivery API becomes unavailable.\nActions: contain, diagnose, recover using approved runbook.\nEvidence: timeline, restore result and actual RPO/RTO.\nFollow-up: regression story with owner and deadline.\nRecovery acceptance: Pending (example only).', },
]
export type Template = typeof templateDefinitions[number] & { content: string }
