import Link from 'next/link'
export default function Home() {
  return <main><header><Link href="/" className="brand"><span className="mark">D</span> Delivery Studio</Link><nav><Link href="/sdlc">Lifecycle & templates</Link><Link href="/pipeline" className="button small">Open workspace ↗</Link></nav></header>
    <section className="hero"><span className="eyebrow">YOUR SOFTWARE DELIVERY WORKSPACE</span><h1>From a good idea.<br/><span>To a reviewed release.</span></h1><p>Bring requirements, review suggestions and feedback into one AI-assisted lifecycle. Keep people in control and evidence alongside every change.</p><div className="actions"><Link className="button" href="/pipeline">Enter Delivery Studio ↗</Link><Link className="text-link" href="/sdlc">Explore AI SDLC & templates →</Link></div><div className="badge"><span/> Generic platform · Local increment</div></section>
    <section className="overview"><div><span className="number">01</span><p>Shared delivery lifecycle</p></div><div><span className="number">14</span><p>Reusable document templates</p></div><div><span className="number">Human</span><p>Accountable review decisions</p></div></section>
    <section className="content"><div className="section-heading"><div><span className="eyebrow">BUILD THE PLATFORM ONCE</span><h2>A workspace for every project.</h2></div></div><div className="grid"><article className="card"><div className="card-top"><span className="pill">Requirements</span><span>01</span></div><h3>Feed the next increment</h3><p>Capture backlog items, review findings and showcase feedback. Preserve source history and let AI propose changes for human review.</p><footer><Link href="/pipeline">Open intake →</Link></footer></article><article className="card"><div className="card-top"><span className="pill">Governance</span><span>02</span></div><h3>Use a shared playbook</h3><p>Plan stories and sprints, review design and code security, showcase outcomes, and retain evidence using consistent templates.</p><footer><Link href="/sdlc">Explore the lifecycle →</Link></footer></article><article className="card"><div className="card-top"><span className="pill">Project context</span><span>03</span></div><h3>Add the product when ready</h3><p>Supply a versioned project objective, constraints and backlog. The engine keeps its review rules while adapting to the work.</p><footer>Project-specific scope<span>↗</span></footer></article></div></section>
    <section className="workflow"><span className="eyebrow">A TRACEABLE PATH THROUGH DELIVERY</span><h2>AI prepares. People decide.</h2><div className="steps"><div><b>01 / Define the work</b><p>Describe the outcome, identify conflicts and agree the acceptance criteria.</p></div><div><b>02 / Review the change</b><p>Approve the sprint and security design, verify implementation, and review the resulting evidence.</p></div><div><b>03 / Learn from the showcase</b><p>Review each increment and return feedback to the backlog with its original context.</p></div></div></section><footer className="site-footer"><span>Delivery Studio · Generic AI SDLC</span><span>Working local increment · Production qualification pending</span></footer>
  </main>
}
