import Link from 'next/link'
import { headers } from 'next/headers'
import { randomUUID } from 'node:crypto'
import { getPayload } from 'payload'
import config from '@payload-config'
import { role } from '../../../security'
import { digest, validateTriage } from '../../../sdlc/contracts'
import { submitIntake, queueTriage, reviewTriage } from './actions'
import SubmitButton from './SubmitButton'
import { activeProject } from '../../../sdlc/project'
import './pipeline.css'
import StoryReviews from './StoryReviews'
export const dynamic = 'force-dynamic'
export default async function Pipeline({ searchParams }: { searchParams: Promise<{ notice?: string }> }) {
  const payload = await getPayload({ config })
  const { user } = await payload.auth({ headers: await headers() })
  if (role(user) !== 'admin') return <main className="pipeline"><header><Link href="/" className="brand">Delivery Studio</Link><Link href="/sdlc">Templates ↗</Link></header><section className="welcome"><span className="eyebrow">AI SOFTWARE DELIVERY</span><h1>A clear path from<br/>idea to evidence.</h1><p>Manage requirements, review AI suggestions and keep human decisions in control.</p><Link className="button" href="/admin/login?redirect=%2Fpipeline">Sign in as a delivery administrator →</Link><p className="muted">Delivery records are private. Only delivery administrators can access this workspace.</p></section></main>
  const project = await activeProject()
  const projectFilter = { projectKey: { equals: project.key } }
  const [intake, runs, decisions] = await Promise.all([
    payload.find({ collection: 'sdlc-intake', where: projectFilter, user, overrideAccess: false, sort: '-id', limit: 100, depth: 0 }),
    payload.find({ collection: 'sdlc-runs', where: projectFilter, user, overrideAccess: false, sort: '-id', limit: 20, depth: 0 }),
    payload.find({ collection: 'sdlc-decisions', where: projectFilter, user, overrideAccess: false, sort: '-id', limit: 100, depth: 0 }),
  ])
  const { notice } = await searchParams
  const notices: Record<string, string> = { submitted: 'Input recorded. Its source and content hash are preserved.', queued: 'Triage queued. The separate worker will process this exact snapshot.', reviewed: 'Your review decision was recorded against the result hash.' }
  return <main className="pipeline"><header><Link href="/pipeline" className="brand"><span className="mark">D</span> Delivery Studio</Link><nav><Link href="/sdlc">Lifecycle & templates</Link><Link href="/admin">Administration ↗</Link></nav></header>
    <section className="pipeline-heading"><div><span className="eyebrow">{project.name.toUpperCase()} / DELIVERY CONTROL</span><h1>Make the next<br/><span>good change.</span></h1><p>One intake for requirements, review findings and showcase feedback. AI proposes. People decide.</p></div><div className="scope-card"><span className="pill">Local engine increment</span><h3>{project.name}</h3><p>{project.objective}</p><small>Project profile v{project.version} · Human approval gates apply to every project.</small></div></section>
    {notice && notices[notice] && <p className="notice" role="status">{notices[notice]}</p>}
    <section className="delivery-metrics" aria-label="Delivery summary"><div><b>{intake.totalDocs}</b><span>Traceable inputs</span></div><div><b>{runs.totalDocs}</b><span>Triage runs</span></div><div><b>{runs.docs.filter(r => r.status === 'awaiting-review' && !decisions.docs.some(d => d.run === r.id)).length}</b><span>Awaiting human review*</span></div><div><b>{decisions.totalDocs}</b><span>Recorded decisions</span></div></section><p className="muted">*Review count covers the latest 20 runs and latest 100 decisions. No code deliveries or production releases are inferred from triage.</p>
    <section className="delivery-columns"><div className="delivery-panel"><span className="eyebrow">01 / FEED THE PIPELINE</span><h2>What should change?</h2><p>Describe the outcome and how you would verify it. Use synthetic information in this local increment.</p><form action={submitIntake} className="intake-form"><input type="hidden" name="submissionKey" value={randomUUID()}/><input type="hidden" name="projectKey" value={project.key}/><input type="hidden" name="contextHash" value={digest(project)}/><label>Input type<select name="kind"><option value="requirement">Backlog requirement</option><option value="review">Review suggestion</option><option value="feedback">Showcase feedback</option></select></label><label>Title<input name="title" required maxLength={200} placeholder="Describe the next useful capability"/></label><div className="field-pair"><label>Target story or milestone<input name="target" required maxLength={120} placeholder="ST-001"/></label><label>Source or review reference<input name="origin" required maxLength={200} placeholder="MVP review / synthetic example"/></label></div><label>Outcome, acceptance criteria or finding<textarea name="content" required maxLength={12000} rows={6} placeholder="Given a user need, when the feature is used, then the expected outcome is verified…"/></label><SubmitButton>Record input →</SubmitButton></form></div>
    <div className="delivery-panel"><span className="eyebrow">02 / UNDERSTAND THE CHANGE</span><h2>Backlog & feedback</h2><p>Original records remain unchanged. Revised requirements should reference the previous input in their source description; structured supersession is available in the admin collection.</p>{intake.docs.length ? <><form action={queueTriage}><input type="hidden" name="contextHash" value={digest(project)}/><SubmitButton>Queue AI triage of current intake →</SubmitButton></form><div className="intake-list">{intake.docs.map(i => <article key={i.id}><div><span className="pill">{i.kind}</span><small>IN-{i.id} · {i.target}</small></div><h3>{i.title}</h3><p>{i.content}</p><small>{i.origin} · SHA-256 {i.sourceHash.slice(0, 12)}…</small></article>)}</div></> : <div className="delivery-empty"><h3>Your next increment starts here</h3><p>Add a requirement, a review finding or MVP feedback. AI triage will link duplicates and surface decisions before work starts.</p></div>}</div></section>
    <section className="delivery-panel runs-panel"><span className="eyebrow">03 / REVIEW THE EVIDENCE</span><h2>AI proposals & human decisions</h2><p>Triage acceptance accepts analysis only. Sprint, design security, code security, MVP and release approvals stay separate.</p>{!runs.docs.length && <p className="delivery-empty">No runs yet. Submit input, queue a snapshot, then run the separate worker.</p>}{runs.docs.map(run => {
      const reviewed = decisions.docs.find(d => d.run === run.id)
      let result = null
      try { if (run.result && Array.isArray(run.snapshot)) result = validateTriage(run.result, run.snapshot.map(x => String((x as { id: number }).id))) } catch { /* invalid results never render as actionable proposals */ }
      return <article className="run-card" key={run.id}><div className="run-heading"><h3>RUN-{run.id}</h3><span className={`run-status ${run.status}`}>{run.status.replaceAll('-', ' ')}</span></div><p className="muted">Snapshot {run.taskKey.slice(0, 16)}… · {run.elapsedMs != null ? `${(run.elapsedMs / 1000).toFixed(1)} seconds` : 'Not timed yet'} · Cost unavailable</p>{run.failure && <p role="alert" className="failure">{run.failure}</p>}{result && <><div className="proposal-grid">{result.proposals.map((p, index) => <div key={index} className="proposal"><span className="pill">{p.disposition}</span><h4>{p.title}</h4><p>{p.rationale}</p><small>Sources: {p.sourceIds.map(id => `IN-${id}`).join(', ')}</small></div>)}</div>{result.conflicts.length > 0 && <div className="conflicts"><h4>Human decisions needed</h4><ul>{result.conflicts.map((c, i) => <li key={i}>{c}</li>)}</ul></div>}<details><summary>Evidence & result checksum</summary><p className="hash">{run.resultHash}</p><pre>{JSON.stringify(run.result, null, 2)}</pre></details></>}{reviewed ? <div className="review-record"><b>{reviewed.decision === 'accept-triage' ? 'Analysis accepted' : 'Findings returned'}</b><p>{reviewed.notes}</p><small>Human actor #{String(reviewed.actor)} · {new Date(reviewed.createdAt).toLocaleString('en-AU', { timeZone: 'Australia/Sydney' })} Sydney</small></div> : run.status === 'awaiting-review' && result && <form action={reviewTriage} className="review-form"><input type="hidden" name="run" value={run.id}/><input type="hidden" name="scopeHash" value={run.resultHash || ''}/><label>Review notes<textarea name="notes" required maxLength={4000} rows={2} placeholder="Record resolved conflicts, findings and follow-up inputs."/></label><div className="actions"><SubmitButton name="decision" value="accept-triage">Accept analysis</SubmitButton><SubmitButton name="decision" value="return-findings" secondary>Return findings</SubmitButton></div></form>}</article>
    })}</section><StoryReviews payload={payload} user={user!} projectKey={project.key}/><section className="worker-boundary"><h3>Implementation runner readiness</h3><p>Intake analysis executes through the authenticated CLI worker. Code execution is blocked until worker and verifier isolation are demonstrated. No container runtime was found in the initial environment check. An isolated checkout alone cannot protect approval credentials or host secrets.</p></section><footer className="site-footer"><span>Delivery Studio · Working local increment</span><Link href="/sdlc">Explore all 14 document templates →</Link></footer>
  </main>
}
