/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    authors: Author;
    articles: Article;
    'sdlc-intake': SdlcIntake;
    'sdlc-runs': SdlcRun;
    'sdlc-decisions': SdlcDecision;
    'sdlc-stories': SdlcStory;
    'sdlc-gates': SdlcGate;
    'sdlc-tasks': SdlcTask;
    'sdlc-task-events': SdlcTaskEvent;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    'sdlc-intake': SdlcIntakeSelect<false> | SdlcIntakeSelect<true>;
    'sdlc-runs': SdlcRunsSelect<false> | SdlcRunsSelect<true>;
    'sdlc-decisions': SdlcDecisionsSelect<false> | SdlcDecisionsSelect<true>;
    'sdlc-stories': SdlcStoriesSelect<false> | SdlcStoriesSelect<true>;
    'sdlc-gates': SdlcGatesSelect<false> | SdlcGatesSelect<true>;
    'sdlc-tasks': SdlcTasksSelect<false> | SdlcTasksSelect<true>;
    'sdlc-task-events': SdlcTaskEventsSelect<false> | SdlcTaskEventsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  role: 'editor' | 'publisher' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: number;
  name: string;
  sourceKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: number;
  title: string;
  body: string;
  visibility: 'private' | 'public';
  author: number | Author;
  relatedArticles?: (number | Article)[] | null;
  sourceKey?: string | null;
  sourceHash?: string | null;
  importedHash?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-intake".
 */
export interface SdlcIntake {
  id: number;
  projectKey?: string | null;
  contextHash?: string | null;
  submissionKey: string;
  title: string;
  kind: 'requirement' | 'review' | 'feedback';
  content: string;
  target: string;
  origin: string;
  supersedes?: (number | null) | SdlcIntake;
  sourceHash: string;
  actor: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-runs".
 */
export interface SdlcRun {
  id: number;
  projectKey?: string | null;
  projectContext?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contextHash?: string | null;
  taskKey: string;
  status: 'queued' | 'running' | 'awaiting-review' | 'failed';
  snapshot:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  result?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  resultHash?: string | null;
  failure?: string | null;
  elapsedMs?: number | null;
  toolVersion?: string | null;
  exitCode?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-decisions".
 */
export interface SdlcDecision {
  id: number;
  projectKey?: string | null;
  decisionKey: string;
  run: number | SdlcRun;
  scopeHash: string;
  decision: 'accept-triage' | 'return-findings';
  notes: string;
  actor: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-stories".
 */
export interface SdlcStory {
  id: number;
  projectKey: string;
  contextHash: string;
  storyKey: string;
  title: string;
  contract:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  supersedes?: (number | null) | SdlcStory;
  revision: number;
  versionKey: string;
  scopeHash: string;
  actor: number | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-gates".
 */
export interface SdlcGate {
  id: number;
  story: number | SdlcStory;
  projectKey: string;
  scopeHash: string;
  kind: 'sprint' | 'design-security' | 'code-security' | 'outcome' | 'mvp';
  decision: 'accept' | 'reject';
  notes: string;
  actor: number | User;
  decisionKey: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-tasks".
 */
export interface SdlcTask {
  id: number;
  taskKey: string;
  story: number | SdlcStory;
  projectKey: string;
  scopeHash: string;
  status: 'queued' | 'reserved' | 'uncertain' | 'awaiting-verification' | 'exhausted';
  owner?: string | null;
  fence: number;
  attemptCount: number;
  leaseExpiresAt?: string | null;
  deadlineAt?: string | null;
  resultHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-task-events".
 */
export interface SdlcTaskEvent {
  id: number;
  eventKey: string;
  task: number | SdlcTask;
  attempt: number;
  fence: number;
  owner?: string | null;
  kind: 'queued' | 'claimed' | 'heartbeat' | 'uncertain' | 'candidate' | 'recovered';
  evidenceHash?: string | null;
  actor?: (number | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'authors';
        value: number | Author;
      } | null)
    | ({
        relationTo: 'articles';
        value: number | Article;
      } | null)
    | ({
        relationTo: 'sdlc-intake';
        value: number | SdlcIntake;
      } | null)
    | ({
        relationTo: 'sdlc-runs';
        value: number | SdlcRun;
      } | null)
    | ({
        relationTo: 'sdlc-decisions';
        value: number | SdlcDecision;
      } | null)
    | ({
        relationTo: 'sdlc-stories';
        value: number | SdlcStory;
      } | null)
    | ({
        relationTo: 'sdlc-gates';
        value: number | SdlcGate;
      } | null)
    | ({
        relationTo: 'sdlc-tasks';
        value: number | SdlcTask;
      } | null)
    | ({
        relationTo: 'sdlc-task-events';
        value: number | SdlcTaskEvent;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  sourceKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  visibility?: T;
  author?: T;
  relatedArticles?: T;
  sourceKey?: T;
  sourceHash?: T;
  importedHash?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-intake_select".
 */
export interface SdlcIntakeSelect<T extends boolean = true> {
  projectKey?: T;
  contextHash?: T;
  submissionKey?: T;
  title?: T;
  kind?: T;
  content?: T;
  target?: T;
  origin?: T;
  supersedes?: T;
  sourceHash?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-runs_select".
 */
export interface SdlcRunsSelect<T extends boolean = true> {
  projectKey?: T;
  projectContext?: T;
  contextHash?: T;
  taskKey?: T;
  status?: T;
  snapshot?: T;
  result?: T;
  resultHash?: T;
  failure?: T;
  elapsedMs?: T;
  toolVersion?: T;
  exitCode?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-decisions_select".
 */
export interface SdlcDecisionsSelect<T extends boolean = true> {
  projectKey?: T;
  decisionKey?: T;
  run?: T;
  scopeHash?: T;
  decision?: T;
  notes?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-stories_select".
 */
export interface SdlcStoriesSelect<T extends boolean = true> {
  projectKey?: T;
  contextHash?: T;
  storyKey?: T;
  title?: T;
  contract?: T;
  supersedes?: T;
  revision?: T;
  versionKey?: T;
  scopeHash?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-gates_select".
 */
export interface SdlcGatesSelect<T extends boolean = true> {
  story?: T;
  projectKey?: T;
  scopeHash?: T;
  kind?: T;
  decision?: T;
  notes?: T;
  actor?: T;
  decisionKey?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-tasks_select".
 */
export interface SdlcTasksSelect<T extends boolean = true> {
  taskKey?: T;
  story?: T;
  projectKey?: T;
  scopeHash?: T;
  status?: T;
  owner?: T;
  fence?: T;
  attemptCount?: T;
  leaseExpiresAt?: T;
  deadlineAt?: T;
  resultHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sdlc-task-events_select".
 */
export interface SdlcTaskEventsSelect<T extends boolean = true> {
  eventKey?: T;
  task?: T;
  attempt?: T;
  fence?: T;
  owner?: T;
  kind?: T;
  evidenceHash?: T;
  actor?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}